---
- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars_files:
    - host_vars/vars.yml
    - host_vars/vault.yml
  tasks:
    - name: Provision EC2 instance (Ubuntu 18.04 HVM)
      ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        key_name: "{{ keypair }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        count_tag:
          Name: "{{ instance_name }}"
        instance_tags:
          Name: "{{ instance_name }}"
      register: ec2
